/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY BY HAND! */
#ifndef __/HOME/MIT/AUVCL_COVERAGE/PROBABILISTIC_COVERAGE/SRC/PROBABILISTIC_COVERAGE.H__
#define __/HOME/MIT/AUVCL_COVERAGE/PROBABILISTIC_COVERAGE/SRC/PROBABILISTIC_COVERAGE.H__

#include "CoverageSensor.h"
#include "XYCoverageMap.h"
#include "PDF.h"

#endif //__/HOME/MIT/AUVCL_COVERAGE/PROBABILISTIC_COVERAGE/SRC/PROBABILISTIC_COVERAGE.H__ 
